### ISSUE TITLE
執筆者募集

### ISSUE THREAD

**Issue by kiridaruma** [imas/imasbook#1]
合同本に参加したい方は、

- 著者名
- タイトル(仮でも内容がわかるもの)
- その他(どれくらい書くかとか、他に留意してほしいこと)

をコメントで書き込んでください
(書き込んだら、一応本決定となります)

↓例(自分の場合)、

---

アイマス楽曲を歌詞解析してみた話
(きりだるま)

歌詞解析の結果の表とかを張りたいので、ちょっとページ数増えるかもです

---

**Comment by mh35** [comment]
著者名 MH35
タイトル アイドルと学ぶホームページの作り方(仮)
Webサーバ借りて、CMS(WordPressの予定)導入して、テンプレート作って、拡散のためのタグの説明をして、なのでだいぶ長くなると思います。

**Comment by yuki-hevx86** [comment]
著者名：ヘヴろく
タイトル：李衣菜のヘッドホンアンプを作ってあげる（仮）
OPアンプ選んで、SPICEモデル使ってシミュレーションして、
基板アートワークまでやる話を書こうと思います。

**Comment by crssnky** [comment]
- 著者名:croMisa
- タイトル:im@sparqlのなにか(未定)

ドキュメントサイトみたいなのも作ってしまったので差別化を図りたいけど、どれくらいのページ数が良いでしょう...?

**Comment by papix** [comment]
著者名: papix(仮)
タイトル: ライブの予習を自動的に作る試み (仮)

ライブの出演者と過去の参加楽曲から, ライブの予習曲リストを自動的に生成する試みをしようと思っているのでそれの中間報告(?)をします. ページ数は少ないと思われる.

**Comment by kiridaruma** [comment]
流石にもう間に合わないと思うので、締め切りますー
