### ISSUE TITLE
デザイン要望や質問の募集

### ISSUE THREAD

**Issue by takanakahiko** [imas/imasbook#13]
- デザインについて要望がアレばこちらにお願いします．
- 基本的にCSSによる指定なので，CSSでそのまま要望を出してもらってもいいです
- 「これできる？」みたいなのもガンガン言ってください!

**Comment by takanakahiko** [comment]
過去の質問

- テキスト的な改行( `<br>` )は、使わない方がいい？
- そうです

- 改行後，一文字あけるルールを一時的に無くせる？
- CSSのルールで，画像やコードの後ろのインデントを消すことは可能です

- サイズは?
- A5 です

- 画像が飛び出しています
- 最新のmasterブランチでは修正されて，`max-width:100%;` となっています

- 数式は対応していませんか？
- いまから追加実装で対応可能ですが，フォント等の不具合がこわい...(画像だと嬉しいです)

**Comment by kiridaruma** [comment]
自分の章ですが、解析結果の欄(![see also](https://github.com/imas/imasbook/pull/14/files#diff-d0fe7db067c655f4659ff604471623b7R87))のスタイルをちょっと調整したいなぁって思ってます
具体的には

- 行番号を付けたい(優先度低め)
- 複数の行にまたがらずに1ページで表示したい(優先度高め)

あたりです
どうでしょうか？

**Comment by takanakahiko** [comment]
これは章の開始を右ページに統一するために生まれた余白ページだと思います．

**Comment by takanakahiko** [comment]
とじます〜
