### ISSUE TITLE
あとがきとアイコン

### ISSUE THREAD

**Issue by takanakahiko** [imas/imasbook#18]
あとがきとアイコンを収集する必要があるので，忘れないように建てました．
集め方決まり次第連絡します．

**Comment by takanakahiko** [comment]
@crssnky @mh35 @kiridaruma @papix @yuki-hevx86 

おまたせしました！

- 名義(ex: `takanakahiko` )
- アイコン(ex: `https://pbs.twimg.com/profile_images/872483352304959488/wQsdxU4b_400x400.jpg` )
- 50文字程度あとがき( `デザインを考えたり，CSS組版をしたりしてお手伝いさせていただきました!CSS組版の良さや課題が見えてきたので，とても有意義な時間でした．` )

**Comment by mh35** [comment]
* 名義 MH35
* アイコン ![yuriko_gs](https://user-images.githubusercontent.com/1467893/49690897-807c9e80-fb7b-11e8-8e49-978e45544828.png)
* 担当 矢吹可奈 森久保乃々 櫻木真乃
* あとがき
    > 非常にスケジュールがかつかつでしたがどうにか書き上げることができました

**Comment by mh35** [comment]
あ、ちなみにアイコンは百合子です(前同人誌の原稿で使おうとしたやつだったはず)

**Comment by yuki-hevx86** [comment]
よろしくお願いします。

- 名義：へヴろく
- [アイコン](https://drive.google.com/file/d/1uO-rRbKsN2EHaJLxWttY94bww4RjYpYp/view?usp=sharing)
- 担当：神崎蘭子　多田李衣菜　前川みく
- あとがき：`この本をきっかけに電子工作に興味を持ってもらえればと思い執筆しました。闇に飲まれよ！！`

**Comment by crssnky** [comment]
- 名義:croMisa
- アイコン:![default](https://user-images.githubusercontent.com/10788283/49698076-44405100-fc02-11e8-9816-6ed6a82b151e.png)
- 担当:如月千早
- あとがき:`2018年はim@sparqlが飛躍した年なので、締めくくりに物理的な何かが残るのは嬉しいです。`

**Comment by takanakahiko** [comment]
全員分集まったので締めます！ご協力ありがとうございました！
