### ISSUE TITLE
今後のスケジュールと、役割分担、原稿フォーマットの決定

### ISSUE THREAD

**Issue by kiridaruma** [imas/imasbook#2]
## スケジュール

とりあえずC95(2018年冬コミ)に出すというゴールはほぼ決定
その上で、原稿締め切り日の設定が一番大事(なはず)

現状では、「当日6週間前の11/21(mh35さん)」とのことだけど、これについては本を刷ったことある方の意見を聞きながら設定したい
あまり時間はないので、**とりあえず9/24までにこのissueの議題を解決する**は決定としておく

## 役割分担

絶対に必要となる役割としては

- 全体の進捗を見て管理する人
    - 全体のスケジュール管理と、締め切り近づいてきたらお尻に火をつける人
    - 最悪@kiridarumaがそのままやります
- 原稿をまとめて一つのデータにする人 (Done. @takanakahiko )
    - ここは一度技術誌を書いたことのある方にお任せしたい...
- 印刷等を担当する人
    - 本を刷ったことある方にお任せしたいけど、初めての人でもなんとかなりそう (Done. @yuki-hevx86)

あたり

この3人を決めてしまえば、それぞれが主導して動いていくと思う

## 原稿フォーマット

基本的に「原稿をまとめて一つのデータにする人」が主導で決定
今のところ

- TeX
- markdownで書いて、最終的に何かに変換
- [ReVIEW](https://github.com/kmuto/review)

あたりが候補
ただ、様々なスキルセットや経歴を持った方がいるので、そのあたりに考慮したい
担当の人が「これが一番いい！」と思ったので良いと思う

Done. Markdown→何か→pdfの形式
原稿はMarkdown

**Comment by mh35** [comment]
Markdownでやるにあたって気になるのは、複数のファイルを読み込んで1つのPDFを生成できるか、という点です。
LaTeXでやる場合、\\includeを使うことで複数ファイルに対応することが可能ですが、似たような機能がMarkdownにありますでしょうか？

**Comment by takanakahiko** [comment]
> Markdownでやるにあたって気になるのは、複数のファイルを読み込んで1つのPDFを生成できるか、という点です。
> LaTeXでやる場合、\includeを使うことで複数ファイルに対応することが可能ですが、似たような機能がMarkdownにありますでしょうか？

これですが，`markdown -> PDF` ではなく， `markdown -> ??? -> PDF` なので， `markdown -> ???` の過程で原稿をマージすれば大丈夫だと考えています．

**Comment by mh35** [comment]
なるほど。確かに、それなら大丈夫ですね。

**Comment by yuki-hevx86** [comment]
原稿フォーマットについてはmarkdownが良いと思います。

**Comment by kiridaruma** [comment]
印刷関連は @yuki-hevx86 が担当

**Comment by takanakahiko** [comment]
このリポジトリのLICENSEどうしましょう

**Comment by mh35** [comment]
LICENSEはとりあえず執筆者およびim@stadyに帰属させるとして、MITとかBSDとかはどうしましょうか

**Comment by kiridaruma** [comment]
コード(markdown→pdf化周り)は良いんですが、原稿は転用ダメってところは明確にしたいですねー
コードと執筆物は扱いがまた違うと思いますし

**Comment by takanakahiko** [comment]
原稿作成周りに関しては， [こちら](https://github.com/takanakahiko/markdown-css-typesetting/blob/master/LICENSE.txt) で示しています

**Comment by takanakahiko** [comment]
基本的に，リポジトリはパブリックドメインor WTFPLでいいと思います．
また， `articles/` 内に `LICENSE.txt` ファイルを設置すれば，基本的にそのディレクトリには違うライセンスを適用できるので，その方向で考えればいいと思います．

例
```
1. リポジトリのルートディレクトリに `LICENSE.txt` (WTFPL)を設置
2. リポジトリの `articles/` ディレクトリに `LICENSE.txt` (MIT)を設置
3. リポジトリトップのREADMEにその旨を書く
```

**Comment by takanakahiko** [comment]
_WTFPL_ は人によっては下品と感じると思うでしょうし， _MIT_ も特に理由はないので，LICENSEの内容に関しては話し合いたいところです

**Comment by kiridaruma** [comment]
第一回企画、お疲れ様でしたー
