### ISSUE TITLE
第一回企画振り返り

### ISSUE THREAD

**Issue by kiridaruma** [imas/imasbook#24]
新年あけましておめでとうございます。
あと、C95お疲れ様でした！

ハッカソンの方と同じ感じで、KPTで振り返りをやっていこうと思います
あと、必要があればどこかしらで通話とかする機会を設けてもいいかもしれないですねー

**Comment by kiridaruma** [comment]
## Keep

- 無事に終わってよかった...
- 数もそれなりに捌けたので、初参加としてはかなり良かったのではないかなと
- 週刊は無理ですが、定期的に出していきたいですねー

## Problem

- 役割が特定の人に集中してしまった
  - 特になかひこさん
  - 自分自身、本を初めて出すというのもあったけど、今回の経験を共有して次はもっと良くしたい

## Try

- 「勝手に本が出来上がる仕組み」を作りたい
  - 予定進行や役割分担のテンプレートを作って、人が集まったら自動的に本ができる...みたいな
- もっと人を増やしたい！
  - 10人とか20人とかの分厚い本とか出してみたい！
  - 金銭的にも、参画者が増えると一人当たりの負担が減る！

## その他

とにかく無事に終わってよかったです...
頒布数も上々と思うし、初回にしては大成功だったんではないかなと

自分自身、本なんて出したことないのに旗振りみたいなことをやってましたが、いろいろな人に助けてもらってほんと感謝です
次回もどこかで本を出す流れっぽいので、そこも参加したいなぁ

**Comment by takanakahiko** [comment]
## Keep

- 早割入稿できて良かったと思います thx @kiridaruma @papix @mh35 @yuki-hevx86 @crssnky 
- レビューがうまく働いていた thx @takemikami @YutaGoto @takayamaki
- 黒字になってよかった(100部にしようと言っていた手前，内心ビクビクしていた)
- 絵を先に書いてもらったのはモチベーション的にかなり良かった

## Problem

- テンプレートに課題があった
  - 導入時点では未完成で，運用でカバーする場面が多かった
  - CSSが完全にオレオレになっていて自分しか手を付けられなくなっていた
- 売上の管理とか在庫の管理とか印刷代の集金とか，大事なものがギリギリで決まるのは良くないな〜と思った
- 入稿や組版について，「ナレッジシェア」より「完成」を優先させすぎて，役割分担ができなかった
- 表紙のスペルミス等の確認漏れがあった

## Try

- 今回のお金面のことを(関係者の同意が取れたら)すべて残したい
- [テンプレートのリポジトリ](https://github.com/takanakahiko/markdown-css-typesetting)を整理して，他の人のコントリビューションを受け入れる体制を作りたい
  - CIでバアアアンってPDF吐き出したい...吐き出したくない?
  - CSSmarkdownのパーサーを変えたい
  - etc...
- 最速入稿して値引きを狙っていきたい(いまから次の企画しよう!)

## その他

僕個人の反省点としては `入稿や組版について，「ナレッジシェア」より「完成」を優先させすぎて，役割分担ができなかった` に濃縮されていて，本当に申し訳ないです...

でも，本当に素晴らしい本ができたと思っていて非常に誇らしいです．うまくジャンルがバラけていましたし， レビューがうまく働いていたしで，複数人で書くメリットが最大限に活きていて非常に楽しかったです！

機会があったらまた参加したいです！

**Comment by crssnky** [comment]
## Keep
- 予定通りのスケジュール
  - 今回のスケジューリングを参考として記録にまとめたい感
- ボリューミーな50ページ
  - ハッチがポッチするジャンル数
- 外野からのレビュー
  - お忙しい中お世話になりました
- 次刊もありそうな現刊の雰囲気
  - 今回参加してない人からも「面白そう、次は参加したい」って思ってもらえるのは良い

## Problem 
- コミケとか同人誌とかに馴染みがなさすぎて、進行をほぼ投げてしまってた(ROM専)
  - 原稿以外も進行してくださったみなさんありがとうございました
- 誤字の見逃し
  - 先日の「Idle」もそうだけど、絵って見た目の華やかさに気を取られてテキスト疎かになるね

## Try
- 次刊
- 効率的な宣伝
  - ツイート以外の方法(Webページとか？)

## その他
進行や絵師さんの交渉、組版

**Comment by yuki-hevx86** [comment]
## Keep
- 無事間に合った事
- インパクトのある内容
- 数が出てよかった

## Problem
- ギリギリで印刷の対応を投げてしまった。申し訳ありません。
- 決め事、特にお金関係が後々決まるのは危ないと思いました。
- 特定の方へ役割が偏ってしまった。

## Try
- お金と在庫の管理をシステム化したい。
　takanakahikoの仰る通りでお金の流れはすべて記録しておきたいです。

## その他
C95の所感です。表紙買いしてくださる方が多数いらっしゃいました。
その他は指名買いの方です。

声かけ重要ですね、hamacoさん心強かったです。

手を取ってもらえても頒布につながらなかった考察。
- 内容が難しい、または簡単（自分のヘッドホンアンプの記事）と思われた。
- ジャンルが多岐にわたるため１カテのために一冊分出すのかとためらわれた。
- 1500円という価格設定が高い？

続刊がありましたらまた参加させていただきたいと思います。
今回はありがとうございました！

**Comment by papix** [comment]
# K
- 文章書くの面白いですね
    - 次書く時のネタも浮かびました...
- 黒字出たのも良かったですね

# P
- 結構 @takanakahiko さんに頼り切ってしまいましたね...

# T
- 赤字リスク減らすアクション出来ると良いですね
- とっつきやすさ増やすためにエンジニアによる(単純な)二次創作とかも載せても面白そうですね
     - 絵とか小説とか... (二次創作小説書いてみたい気持ちがあるのできっかけが欲しいというのもある)

**Comment by YutaGoto** [comment]
issue( https://github.com/imas/hackathon/issues/92 )を立てるだけたてて何も貢献(執筆/運営)できずすみませんmm **Problem**

## Keep

- いい本だったので次回以降も期待

## Try

> CIでバアアアンってPDF吐き出したい...吐き出したくない?

できそうなきはするが。。

**Comment by WakuwakuP** [comment]
当日お手伝いしただけですが

## Keep
- 無事終わってよかった 

## Problem
- 僕自身記事を書かなかった
- 頒布当日の準備がギリギリだった

## Try
- 次は参加したい
