### ISSUE TITLE
第二回企画 執筆者募集

### ISSUE THREAD

**Issue by kiridaruma** [imas/imasbook#25]
imasbook02ということで、第二回企画は2019/4/14の技術書典への参加を目指してやっていきましょう！
see also https://techbookfest.org/

合同本に参加したい方は、

- 著者名
- タイトル(仮でも内容がわかるもの)
- その他(どれくらい書くかとか、他に留意してほしいこと)

をコメントで書き込んでください
(書き込んだら本決定となります)

**Comment by kiridaruma** [comment]
- 著者名
  - きりだるま
- タイトル
  - アイマスを「証明」してみた話
  - 多分、coqでなんかそれっぽいことをやると思います
- その他
  - 特になし

**Comment by papix** [comment]
- 著者名
    - 遠山賢寿
- タイトル
    - アイドルマスターのメタデータに対するスリーレターコードを利用したユニークなインデックスの提案
    - 曲とかデータ化して処理するときに, 曲名だとブレが生じかねないし数字をユニークキーにすると味気ないのでスリーレターコード使ったらかっこよくない? という提案
- 多分前と同じくらいの量書くと思います

**Comment by WakuwakuP** [comment]
- 著者名
  - Wakuwaku
- タイトル
  - 増え続けるアイマス楽曲をモバイル端末に入れたくない
- その他
  - 特になし

**Comment by kagemiku** [comment]
* 著者名
    * kagemiku
* タイトル
    * うづコインを支える技術　的な
    * うづコインにおけるアイドルチェーンの仕様やS(min)ING! の報酬システムについて雑に書きます
* その他
    * 執筆(寄稿？)するのは人生で初めてなので、いろいろ不手際あるかもです。がんばりマッキントッシュ。

**Comment by takemikami** [comment]
- 著者名
   - みかみん
- タイトル
   - アイドルを知るための自然言語処理
      - TF-IDFでアイドルの重要語を調べる
      - (余裕あれば)カップリングした場合の重要語を、分散表現のコサイン類似度で重み付けして算出してみる
- その他
   - 10ページいかないくらいかな？

**Comment by mh35** [comment]
* 著者名 MH35
* タイトル Heroku+Railsでコンベンションセンターもどきを作ってみた
* その他 12-16ページくらいになるかなと思います

**Comment by crssnky** [comment]
- 著者名: croMisa
- タイトル:im@sparql応用〜UE4編〜
- その他:途中乗車みたいな感じですが頑張ります✌🏼️
