### ISSUE TITLE
第二回企画 役職決め&決めること(決まったこと)

### ISSUE THREAD

**Issue by kiridaruma** [imas/imasbook#28]
## 役職
前回企画の経験や[振り返り](#24 )から、必要な役割として、

- 全体の管理をする人 (@kiridaruma)
  - issueを管理したり考えること纏めたり、その他雑用
  - 前回の反省を生かして、当日参加できる人が良い気がする
- 原稿をまとめる人 (@takemikami)
  - 原稿レビュー纏めたり、その辺を考える人
  - 前回の反省から組版やる人とは分けたほうが良い気がする
- デザインやる人
  - 組版周りの整備や絵師さんとの連携をとる方
  - 前回の反省を生かして、「その人一人でやる」というより「整備してみんなが触れるようにする」という方向で
- 金銭周りの管理をする人(@kagemiku)
  - 印刷所、申し込み等お金が関係してくることとか
  - 前回の反省を生かして、早いうちからしっかり計画を立てたい

あたりを決めた方がいいかなって感じがします。
他に「こういう役割決めたほうが良いんでは？」とか「これ決めないといけないんじゃ？」とかあればコメントに
そのほか、随時決定したこと等もここのコメントに流して記録を残しておきましょう

**Comment by kagemiku** [comment]
## サークル申込みにあたり決めること

* サークル名: IM@Study
* サークルカナ: アイマスタディ
* 公開用ペンネーム: <相談したい> (同じくIM@Study?)
* ジャンル選択: ソフトウェア全般/ハードウェア全般/科学技術/その他  のどれか
* タグ: 執筆内容によって適宜きめる？
* ジャンル詳細: <相談したい>
* 刊行物の種: 1つ
* 持ち込み部数: <相談したい>
* 紹介用Webサイト: <相談したい>

**Comment by kagemiku** [comment]
**前回踏襲するなら**、こんな感じになりそう。

* サークル名: IM@Study
* サークルカナ: アイマスタディ
* 公開用ペンネーム: imasbook
* ジャンル選択: その他
* タグ: Proof, Naming, Mobile, Blockchain, TextMining, Rails, CI
* ジャンル詳細: アイマスハッカソン・アイマスエンジニアMeetupなどから生まれた「アイマス×エンジニア」の作品に携わる有志による合同本
* 刊行物の種: 1つ
* 持ち込み部数: 100
* 紹介用Webサイト: https://imas.connpass.com/

**Comment by kagemiku** [comment]
申込時に使用したサークルカット。

![a0400](https://user-images.githubusercontent.com/3097559/51917392-cb4fbf80-2422-11e9-9a18-18ddb7e1d90f.png)

**Comment by takemikami** [comment]
## 埼玉銭けっと 2019/5/3@川口フレンディアの参加について

以下の条件を満たしたときに参加する方向で考える（ひとまず保留）

- 技術書典終わった後に、既刊の在庫がある
- 銭けっとの申込が締め切られていない

↓埼玉銭けっとの申込期限について

```
申し込み期限はないのですが
先着100サークル申し込み到達次第、募集を中止します。
やや変わった募集方法で恐縮ですが何卒宜しくお願い致します
```

https://zeniket.jimdofree.com/
https://saitamazeniket.jimdofree.com/

**Comment by takemikami** [comment]
## 既刊の頒布について

技術書典6で、既刊(週刊IM@Study 2018/12)も頒布する

- 前回の執筆者の了解(頒布すること)はslack上でとれている
- 既刊の在庫は、takanakahiko が預かっている (受け渡しの段取りは要調整)
- 追加印刷の有無、売上の分配方法については未決定 (既刊の著者で決めて頂ければ。。)

**Comment by takemikami** [comment]
オンラインmtgまとめです。

### 第１回の在庫の頒布

#### 第１回の売上分配について

・第１回の週刊IM@Study在庫もあわせて頒布する
・第１回の参加者側で分配は管理する
　・kagemikuさんから第１回の管理者に売上を渡す
　・第１回の管理者は、第１回企画側で決める

**Comment by kiridaruma** [comment]
imasbook02、無事終了
see also #51
