### ISSUE TITLE
お金関連の事項

### ISSUE THREAD

**Issue by kiridaruma** [imas/imasbook#3]
## 必要となる費用

- 印刷費
- 申し込み費用
    - [mh35](https://github.com/mh35)さんが申し込み済み

その他、後から出てきたら追記します

## 分担方針

基本は執筆者で等分、役割持ちの方は+α

## 値段設定

とりあえず、元がギリギリ取れるかあたりが理想
各種必要費用から逆算して計算するのが良い...? (詳しい方の意見ください)

## お金の集め方、配り方

銀行振込？
ここも詳しい方の意見が欲しい

**Comment by takanakahiko** [comment]
Slackのログをここにメモる

- 手渡しだとログ残らなくてつらいので避ける
- 今回はkyashか振込にしました

あとでお金計算する

**Comment by kiridaruma** [comment]
出た利益の分配まで終了したということで、閉じておきます
