### ISSUE TITLE
第二回企画 金銭周り

### ISSUE THREAD

**Issue by kagemiku** [imas/imasbook#30]
### サークル申し込み
* 7,000円

### 印刷費

**Comment by kagemiku** [comment]
Google スプレッドシート作ったほうがよさそう

**Comment by takemikami** [comment]
オンラインmtgまとめです。

#### かかるお金 (現状認識している分)

- 印刷費 3万円〜
- 表紙デザイン費 3万円〜
- 技術書典の申し込み費 ¥7000

#### お金の回収と分配

- 関係者から等分でお金を集める、売上も等分で分配する
   - これで問題無いかを関係者に確認する

**Comment by YutaGoto** [comment]
印刷代(本100+ポスター2+ポストカード100) = ¥29,020
ゴトウが建て替えています。

**Comment by kiridaruma** [comment]
配分が完了したみたいなのでclose
