### ISSUE TITLE
第二回企画 表紙デザインの準備スレ

### ISSUE THREAD

**Issue by takemikami** [imas/imasbook#31]
表紙デザインのために決めること・決めたことをまとめます。

# 決めるべきこと

- [x] 依頼する絵師さんの決定
- [x] 表紙デザインの方向性： 前回踏襲（週刊アスキー風)するか、他を考えるか？
- [x] 一人か複数か、キーとなるキャラクターの決定
- [x] 表紙キャラクターの服装やポーズ、めがね割狙うか？
- [x] 裏表紙のデザイン誰が担当するか？
- [x] 表紙に記載する文言：全体&各記事のコピー

# 参考

- めがね割(ねこのしっぽ) https://www.shippo.co.jp/neko/info/megane.shtml

**Comment by takemikami** [comment]
オンラインmtgまとめです。

#### 表紙デザインの方向性
- 週刊アスキー風で決定

#### キーとなるキャラクター
- 今週中(2/17週)にSlackでキャラクターを決める

#### 裏表紙のデザイン
- やりたい人・出来る人が居ないかをSlackで聞いてみる

#### 記事のコピーの決定
- 各執筆者に今週中(2/17週)に決めてもらう

**Comment by kiridaruma** [comment]
櫻木真乃がimasbook01の本を持ってる絵ということで決定
3/1に絵師さんからラフ画をもらって、3/5に絵師さんに最終発注

**Comment by takemikami** [comment]
こちらのissue、入稿まで完了しているのでクローズしておきます。
