### ISSUE TITLE
第二回企画 印刷の準備スレ

### ISSUE THREAD

**Issue by takemikami** [imas/imasbook#32]
印刷にあたって決めること・決めたことをまとめます。

# 決めること

- [ ] 印刷所をどこにするか （前回は「ねこのしっぽ」）
- [x] 搬送先をどうするか(直接・自宅)
- [ ] 何部刷るか
- [ ] 用紙やオプション
- [x] 原稿〆切の設定
  - 3/1原稿締め切り

# 参考

## 技術書典のバックアップ印刷所

技術書典のバックアップ印刷所は、以下の２社。
会場への直接搬入してもらえて、トラブルのリスクが少ないので、どちらかで良いと思います。

- 日光企画: http://www.nikko-pc.com/index/top.html
- ねこのしっぽ: https://www.shippo.co.jp/neko/

## 前回の見積

https://imas-hack.slack.com/files/UBKU80D89/FEL3RTZJA/________________________.pdf

前回は以下のオプションをつけた。
- クリアPP加工(+2000) : 表紙がツルツルに
- 大判ポスター(+1900) : 表紙絵をブース後ろor机の前掛けに召喚

## 前回の頒布実績

60部

https://imas-hack.slack.com/files/UBMKU6V5L/FF508T1FZ/____________________log_20181230-100715.pdf

## 原稿〆切の設定

ねこのしっぽの場合、イベント毎の入稿〆切が案内されています。
※日が近づけば技術書典もおそらく掲載されると思います

https://www.shippo.co.jp/nekocore/schedules

**Comment by takemikami** [comment]
オンラインmtgまとめです。

#### 印刷所：
・ねこのしっぽ（眼鏡割もあるので）

#### 搬送先：
・直接会場

#### 何部刷るか：
・100部の方向性で、Slackで全員に確認（前回60部配布）

#### 原稿の〆切：
- 4月14日の１ヶ月前くらいに入稿すると早期割引が受けられる
- 3/1が原稿〆切
- 3/10が最終〆切

**Comment by YutaGoto** [comment]
@YutaGoto がひとまずオンライン入稿の申込みをしようと思います。

|                      |                                                              |
| -------------------- | ------------------------------------------------------------ |
| タイトル             | 週刊IM@Study  【 初版 】                                     |
| サークル名           | IM@Study                                                     |
| ぱっく名             | オンデマンドのぱっく  <br>・ 本のサイズ： A5  <br>・ 申込部数： 100部  <br>・ 綴じ口： 左綴じ  <br>・ 製本方法： 無線綴じ  <br>・ ページ数： 68ページ |
| 表紙仕様             | 表紙印刷： オンデマンド フルカラー  表紙用紙： ホワイトポスト クリアPP加工 |
| 本文仕様             | 本文印刷： オンデマンド 黒1色  本文用紙： 上質紙 70kg        |
| 遊び紙               | 遊び紙： なし  遊び紙用紙：                                  |
| 口絵仕様             | 口絵印刷：   口絵用紙：   挿入枚数：   挿入場所：            |
| その他オプション詳細 | B4卓上ポスター：1枚 表1の原稿で出力 <br>大判ポスター：A2 ノビ [半光沢紙] 1枚 表1の原稿で出力 <br>ポストカード： 100枚 表1の原稿で出力 (裏面：印刷なし) |
| 追加情報             | 現在の料金には1ヶ所までの送料を含みます 発送先：イベント搬入 |
| 主要な納品方法 | イベント搬入                                                 |
| イベント搬入   | 開催日： 2019年4月14日(日) <br>イベント名： 技術書典 6  <br>スペースNo.： か48  <br>搬入先サークル名： IM@Study |
| 分納           | 【分納なし】                                                 |

お金周りは #30 @crssnky くろみささんと相談ですかね

**Comment by YutaGoto** [comment]
https://circleci.com/gh/imas/imasbook/105#artifacts/containers/0 入稿する原稿のやつ

**Comment by takemikami** [comment]
こちらのissue、入稿まで完了しているのでクローズしておきます。
