### ISSUE TITLE
印刷に関することを決める

### ISSUE THREAD

**Issue by takanakahiko** [imas/imasbook#5]
# 決めるべきこと

- [ ] 印刷所をどこにするか
- [ ] 何部刷るか
- [ ] 搬送先をどうするか(直接・自宅)

# 担当

- @yuki-hevx86
- @takanakahiko

**Comment by takanakahiko** [comment]
# 印刷所をどうするか

ここが参考になりそう
http://www.font910.jp/insatsu-jo/

# 何部刷るか

- 何部売れそうか
- お金をいくらまで集金できそうか

で，考えれば良さそう

# 搬送先をどうするか

印刷所が対応している限り，会場に直接搬入してもらうと良さそう．
会場直接搬入だと，手ぶらで会場に行ったら自分のブースにダンボールが置いてあって楽です．

**Comment by takanakahiko** [comment]
なにか疑問点があれば，気軽にここに書き込んでください！
できる限りお答えします！

なるべく @yuki-hevx86 さん主導でできるよう，サポートしていきます．

**Comment by yuki-hevx86** [comment]
**印刷所について**
　⇒何か所かあたってみますが、この辺のおおよその情報が必要と考えます。
　　【例】
　　用紙サイズB5
　　表裏カラーの本文モノクロ
　　紙質をどうするか
　　総ページ数

**何部刷るか**
　⇒imasbookの過去の実績等あればそれに準じて、決めようと思います。
　　なければ、集金額によって印刷できる分だけする。
　　少し余るくらいがちょうどいいのかなと。

**搬送先について**
　⇒手引きにならうと、登録されている印刷所であれば直接搬入可能とのことですが
　　立ち合いが推奨されていたので、その際は当方で現場立会いします。
