### ISSUE TITLE
第三回企画 決まったこと

### ISSUE THREAD

**Issue by kiridaruma** [imas/imasbook#53]
決まったことや、やったことを書いていくスレ

**Comment by subroh0508** [comment]
原稿〆切: 7/22(月)
入稿〆切: 7/27(金) - ねこのしっぽ通常入稿〆切日

(第1回企画の日程に合わせた形)

**Comment by subroh0508** [comment]
とりあえず入稿終わったので、そこまでやったことのログ
各作業どれくらい時間がかかったかをメモしておくので、次回以降のスケジュール管理の一助になればいいなぁ…( ˘ω˘)

### 表紙周り
- 表紙絵決定
   - 6/12開始→6/17未来ちゃん絵投票→6/18確定
   - **案集めから確定まで約1週間**
- 絵師さんとのやりとり by へヴろくさん
   - 見積: 18,900円
   - 7/3下絵チェック(細かな構図確定)→7/8線画チェック→7/11配色チェック→7/12配色チェック(冊子周り)→7/18完成、Uske_sさんにパス
   - **発注から完成まで約3週間から1ヶ月**
- デザイン by Uske_sさん
  - 6/19第2回タイトルで仮組み→7/19第3回タイトルで仮組み→7/25早朝タイトル確定 + ミリシタSSの修正→7/25夜ジャケットぼかし修正(最終稿)
  - 7/22に「ミリシタSS、著作権的に大丈夫？」指摘あり
  - **第3回タイトル仮組みから確定まで約2週間**

### 入稿関連
- 7/26までに全員脱稿(最後の修正が7/25夜)
   - 6/18に執筆のお願い→**全員脱稿まで約1ヶ月 + 1週間**(執筆陣の忙しさ + ライブ予定によって変動しそう)
- 7/27
   - Uske_sさんに入稿作業を依頼
   - 原稿最終調整(記事の順番入れ替え、目次のページ数割り振り、著者表記の抜け修正等)、および入稿用PDFの作成をにしこりが担当
   - 入稿料はオプション含め44,100円(執筆陣6人で割ると7350円、Kyashで集金)
   - 入稿料の詳しい内訳は下記PDF参照

[見積.pdf](https://github.com/imas/imasbook/files/3442751/default.pdf)

**Comment by kiridaruma** [comment]
振り返りについてのissue

https://github.com/imas/imasbook/issues/62

**Comment by kiridaruma** [comment]
imasbook03、お疲れさまでしたー！
次は04(第二回技術同人誌博覧会)に向けて頑張っていきましょうー
