### ISSUE TITLE
第4回企画振り返り

### ISSUE THREAD

**Issue by subroh0508** [imas/imasbook#84]
第2回技術書同人誌博覧会(2019年12月14日)、関係各位お疲れさまでしたー！

- Keep(良かったこと)
- Problem(困ったこと)
- Try(Keep/Problemを踏まえて次やっていきたいこと)

とりあえず立てないと忘れそうだったので立てました。

**Comment by subroh0508** [comment]
## Keep
- 電子版頒布が英断中の英断だった
  - 在庫が出ても場所を取らない！！！
  - 物理本の印刷数絞れてなかったら、今回割とガチで誰か破産してたと思う
  - 自分の記事、実はサンプルレポジトリのcommit hashへのリンクがついてるので、電子版で読むとGitHub上で変更を追いながら読めるようになっている(誰も気づいてなさそうだけど😂)
- 電子決済利用者がかなりいてGood
  - PayPay: 7冊、Pixiv Pay: 1冊(新刊・既刊合わせて)
  - Pixiv Pay、利用者少なすぎ…？？？
- 表紙絵 👍 デザイン 👍 
- コラム追加 👍執筆者開拓が少し前に進んだ
- イベントそのものがめちゃ落ち着いていて神
  - 人の流量がほぼ一定、これが8時間維持され続けていた
  - じっくり吟味してから購入する or しないを決める人がかなり多かった
  - 知り合いや週刊IM@Studyを知らないPとめっちゃ会話できた
  - サークル参加者に昼食出る、懇親会楽しい

## Problem
- 当日お釣り用意するの忘れた
  - コミケだったら確実に死んでた
- 電子の見本誌、間違えて鍵付きZIPのまま出してしまった
- 締切を1週間読み違えてしまい、執筆者各位のお尻を叩くタイミングが遅れてしまった
- 新刊、20冊しか出なかった＞＜
  - 技書博2: 710人
  - 技書典5: 10,300人(Vol.1、Vol.2が完売したイベント)
  - 人数比1/10以下の規模だったので、もしかしたら捌けた方なのかも
- 既刊がまだ70冊くらい残っている、しかも全て物理😢 

## Try
- 今後技書典は毎回申し込みをしていきたい
  - 1番在庫が捌ける確率が高い
  - 実はコミケも比較的売れることが分かった(技術書典の更に15倍の参加者)
  - IM@Studyとして参加→回数増えればサークル参加料も増える
  - 誰かのサークルに委託→回数増えれば委託先サークルの作業量増
     - うまくバランスとりたい…
- 執筆者増やす施策
  - もくもく会 or ハッカソンでの執筆支援タイムしたい！
- 編集部の人が執筆する場合の締切早めたい
  - 早めに設定した方が安心できそう

**Comment by WakuwakuP** [comment]
お疲れ様でしたー^

## Keep

- DLカード良かった
- 売り子のみでの参加でした
- PixivPayで購入したのは僕です
- 当日無事起床成功した
- 弁当おいしかった

## Problem

- DLカードの話を出して放置してしまった
- テーブルクロス欲しい? 欲しくない?
- 今回執筆しなかった
- DLカードの宣伝不足感

## Try

- テーブルクロス作りたくないですか?
- 次は執筆参加!?
- DLカード用にPOPをデカデカと作りたい

**Comment by mh35** [comment]
## Keep

- 今回も無事に本が出た
    - 今回は執筆者数は多くないが100ページ以上という大分量
- 電子書籍はスペースとらない

## Problem

- 大量の売れ残り
    - 冬コミや次の技術書典で私含めどこかのサークルへ委託するという案も考えたほうがよい
- 20部だと3万しか売り上げがないが、7万8000円の支出があり継続的な執筆に問題が発生しそう

## Try

- 知り合いに頼んでもさばく見込みがなくなったときは、合意をとったうえで同人誌業者への委託を検討する(ただ、あまりいい業者がいないのが事実)
- ビルドシステムの刷新

**Comment by UskeS** [comment]
お疲れさまでした！
現地売り子してくださった、にしこりさぶろ〜さん、WakuwakuPさん、ありがとうございました。
# Keep
* 電子版の判断が正しかった
  * 印刷費用の圧縮、在庫管理からの開放
  * DLカードはこだわらなければ100枚刷っても¥1,000で収まる
* デザインさせてもらったものが喜んでもらえてめっちゃうれしい、次もやりたい
* コラムの手軽さ、良かった気がする

# Problem
* 制作物が多くなってきてしまって、副業の繁忙期と重なると死ぬ
  * ただし今回の技書博でデータを作ったため、次回以降は楽なはず
* 印刷手配がやはり後手に回ってしまった（誰かできるひとー！　というこの指とまれ方式）
* コラムの体裁が本文に対してちょっと文字が大きかった？

# Try
* テーブルクロス欲しいかも（デザインする？）
* DLカード用のPOP作りたい（デザインする！）
* 記事執筆参加する
* 印刷手配・入稿担当決めたい
  * ページ数が決まらないと背幅が決まらない→表紙が完成しない、になるので、当面自分？
  * 全然辛くはないが、かといって決して楽ではない😥
* 電子版だとフルカラー発行、URLにハイパーリンク埋め込める（Acrobat Reader）のでメリットが大きい
  * 参加イベントに合わせて物理本の印刷部数をコントロールしたい
  * DLカード（電子版）を宣伝したい

**Comment by crssnky** [comment]
# Keep
- 安定最高の表紙絵！文月さんありがとー！！
- プロの手の表紙の構成！ @UskeS さんありがとうー！ 
- 薄くなくなってサイズが大きくなっても電子版なら安心！
- ミニコラムも差し込めた！

# Problem
- もうちょっと寄稿をギリギリに慌てたくない
- 対象イベントと頒布数
  - なし崩し的に在庫管理が @subroh0508 へ...

# Try
- フルカラーの電子版用PDF
- 需要があったのでim@sparql記事

# その他
- Windows環境でのビルド時のフォント...?

**Comment by ghost** [comment]
# Keep
- デザインから組版までのフローが軌道に乗って良かった
　(@UskeSさんありがとうございます。)
- DL版良いですね。
- 初版以来の執筆でビルドシステム初でしたが、使いやすいので継続お願いします。

# Problem
- イベントによって捌ける数がまちまち。
- 執筆者が少ないかな？（ほどほどに呼び込みたい。）

# Try
- 本文もフルカラーにしてみたい。（物理は印刷費がかさむのでDL版のみで）
- DL版メインにして物理を20くらいに抑える。

**Comment by crssnky** [comment]
振り返り会
https://docs.google.com/document/d/1CU_a39dyYQeo91fLEKjSNbLzG19gpjElTmIXOfseua4/edit
